"""initial schema

Revision ID: 984f13d2acfe
Revises: 
Create Date: 2026-08-25 10:38:25.958842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '984f13d2acfe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'COLLECTING', 'UNDERSTANDING', 'EMBEDDING', 'COMPLETED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('total_prs_synced', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('is_merged', sa.Boolean(), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('milestone', sa.String(length=255), nullable=True),
    sa.Column('release_tag', sa.String(length=255), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changed_files_count', sa.Integer(), nullable=False),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_pr_number', name='uq_repo_pr_number')
    )
    op.create_index(op.f('ix_pull_requests_github_pr_number'), 'pull_requests', ['github_pr_number'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COLLECTING', 'UNDERSTANDING', 'EMBEDDING', 'COMPLETED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('prs_collected', sa.Integer(), nullable=False),
    sa.Column('prs_understood', sa.Integer(), nullable=False),
    sa.Column('documents_created', sa.Integer(), nullable=False),
    sa.Column('embeddings_generated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('changed_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'filename', name='uq_pr_file')
    )
    op.create_table('commits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'sha', name='uq_pr_commit_sha')
    )
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=False)
    op.create_table('discussion_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('comment_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'github_comment_id', name='uq_pr_discussion_comment')
    )
    op.create_table('engineering_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('PR_SUMMARY', 'PR_DESCRIPTION', 'REVIEW_DISCUSSION', 'FILE_CHANGE_SUMMARY', 'ARCHITECTURE_DECISION', 'ISSUE_FIX', name='documenttype'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('repository_name', sa.String(length=512), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('pr_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release', sa.String(length=255), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eng_doc_embedding', 'engineering_documents', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_eng_doc_fts', 'engineering_documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_engineering_documents_author'), 'engineering_documents', ['author'], unique=False)
    op.create_index(op.f('ix_engineering_documents_pr_date'), 'engineering_documents', ['pr_date'], unique=False)
    op.create_index(op.f('ix_engineering_documents_pr_number'), 'engineering_documents', ['pr_number'], unique=False)
    op.create_index(op.f('ix_engineering_documents_release'), 'engineering_documents', ['release'], unique=False)
    op.create_table('linked_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('github_issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'github_issue_number', name='uq_pr_linked_issue')
    )
    op.create_table('pr_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('architectural_change', sa.Boolean(), nullable=False),
    sa.Column('key_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', name='uq_pr_knowledge')
    )
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('diff_hunk', sa.Text(), nullable=True),
    sa.Column('comment_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'github_comment_id', name='uq_pr_review_comment')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('github_review_id', sa.BigInteger(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'github_review_id', name='uq_pr_review')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('review_comments')
    op.drop_table('pr_knowledge')
    op.drop_table('linked_issues')
    op.drop_index(op.f('ix_engineering_documents_release'), table_name='engineering_documents')
    op.drop_index(op.f('ix_engineering_documents_pr_number'), table_name='engineering_documents')
    op.drop_index(op.f('ix_engineering_documents_pr_date'), table_name='engineering_documents')
    op.drop_index(op.f('ix_engineering_documents_author'), table_name='engineering_documents')
    op.drop_index('ix_eng_doc_fts', table_name='engineering_documents', postgresql_using='gin')
    op.drop_index('ix_eng_doc_embedding', table_name='engineering_documents', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('engineering_documents')
    op.drop_table('discussion_comments')
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_table('commits')
    op.drop_table('changed_files')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_pull_requests_github_pr_number'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_table('repositories')
    # ### end Alembic commands ###